version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab_secure_coding_polytron
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - secure_coding_polytron

  secure_coding_polytron:
    image: mysql:8.0
    container_name: mysql_db_secure_coding_polytron
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_secure_coding_polytron
    volumes:
      - db_data_secure_coding_polytron:/var/lib/mysql
      - ./db_secure_coding_polytron.sql:/docker-entrypoint-initdb.d/database.sql:ro
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_secure_coding_polytron
    depends_on:
      - secure_coding_polytron
    ports:
      - "9000:80"
    environment:
      PMA_HOST: secure_coding_polytron
      MYSQL_ROOT_PASSWORD: root
    restart: always

volumes:
  db_data_secure_coding_polytron:
